kazenomatasaburou:
  maxEnergy: 80
  decreaseEnergy: 1
  rechargeEnergy: 2
  rechargeEnergyCT: 40
  minEnergy: 20
  ultHeight: 1.90
  ultTimer: 110
  ultCT: 200
  use_HujinCT: 10
  vector_ratio: 2
  tag: kazenomatasaburou

blender:
  tag: blender
