kazenomatasaburou:
  tag: kazenomatasaburou
  ultReadyTag: kazenomatasaburou_UltReady
  ultTag: kazenomatasaburou_Ulting
  maxEnergy: 80
  decreaseEnergy: 1
  rechargeEnergy: 2
  rechargeEnergyCT: 40
  minEnergy: 20
  ultHeight: 1.90
  ultTimer: 110
  ultCT: 1800
  use_HujinCT: 10
  vector_ratio: 2

blender:
  tag: blender
  ultTag: blender_Ulting
  active_CT: 400
  cMove_Timer: 20
  portal_Timer: 600
  warp_CT: 50
  ult_CT: 2000
